/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.elsdoerfer.keepscore;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        public static final int game_table_padding=0x7f040000;
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int add_new_player=0x7f070006;
        public static final int add_new_scores=0x7f070002;
        public static final int existing_players=0x7f070004;
        public static final int existing_sessions=0x7f070007;
        public static final int existing_sessions_list=0x7f070008;
        public static final int game=0x7f070001;
        public static final int game_container=0x7f070000;
        public static final int new_player_name=0x7f070005;
        public static final int start_game=0x7f070003;
    }
    public static final class layout {
        public static final int game=0x7f030000;
        public static final int setup=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int clear_players=0x7f050005;
        public static final int clear_sessions=0x7f050004;
        public static final int delete_session=0x7f050003;
        public static final int existing_sessions=0x7f050002;
        public static final int new_game=0x7f050001;
        public static final int not_a_valid_number=0x7f050008;
        public static final int start_game=0x7f050007;
        public static final int submit_short=0x7f050006;
    }
    public static final class style {
        public static final int Header=0x7f060000;
    }
}
