/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.elsdoerfer.keepscore;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int add_new_player=0x7f06000e;
        public static final int existing_players=0x7f06000c;
        public static final int existing_sessions=0x7f06000f;
        public static final int existing_sessions_list=0x7f060010;
        public static final int new_player_name=0x7f06000d;
        public static final int start_game=0x7f06000b;
        public static final int widget28=0x7f060000;
        public static final int widget30=0x7f060001;
        public static final int widget31=0x7f060005;
        public static final int widget32=0x7f060007;
        public static final int widget33=0x7f060006;
        public static final int widget34=0x7f060009;
        public static final int widget35=0x7f060008;
        public static final int widget36=0x7f06000a;
        public static final int widget38=0x7f060002;
        public static final int widget39=0x7f060003;
        public static final int widget40=0x7f060004;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int setup=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int clear_players=0x7f040005;
        public static final int clear_sessions=0x7f040004;
        public static final int delete_session=0x7f040003;
        public static final int existing_sessions=0x7f040002;
        public static final int new_game=0x7f040001;
        public static final int start_game=0x7f040007;
        public static final int submit_short=0x7f040006;
    }
    public static final class style {
        public static final int Header=0x7f050000;
    }
}
